---
trigger:
  - main
parameters:
  - name: goal
    displayName: maven goal
    type: string
    default: package
    values:
      - package
      - clean package
      - install
      - clean install
stages:
  - stage: build
    displayName: BuildStage
    pool: 
      name: Default
    jobs:
      - job: maven
        displayName: Build using Maven
        steps:
          - task: Maven@4
            inputs: 
              mavenPOMFile: 'pom.xml'
              goals: ${{parameters.goal}}
          - task: CopyFiles@2
            inputs: 
              contents: 'target/spring-petclinic-3.2.0-SNAPSHOT.jar'
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs: 
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: MyBuildOutputs
